import {mapProjection} from './spatial.mjs';
const $=id=>document.getElementById(id);
let snapshot=null,audio=null,sound=false,lastEvent=null;
function beep(freq=440){if(!sound)return;audio??=new AudioContext();const o=audio.createOscillator(),g=audio.createGain();o.connect(g);g.connect(audio.destination);o.frequency.value=freq;g.gain.setValueAtTime(.07,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.25);o.start();o.stop(audio.currentTime+.25)}
function draw(){
 if(!snapshot)return;const game=snapshot.game,c=$('map'),r=c.getBoundingClientRect(),dpr=window.devicePixelRatio||1;
 c.width=r.width*dpr;c.height=r.height*dpr;const g=c.getContext('2d');g.scale(dpr,dpr);
 const {point,scale}=mapProjection(game.config.play,r.width,r.height),[l,rr,n,f]=game.config.play;
 function box(b,color,label){const [x,y]=point(b[0],b[3]);g.fillStyle=color+'22';g.strokeStyle=color;g.lineWidth=1.5;g.fillRect(x,y,(b[1]-b[0])*scale,(b[3]-b[2])*scale);g.strokeRect(x,y,(b[1]-b[0])*scale,(b[3]-b[2])*scale);g.fillStyle=color;g.font='bold 10px system-ui';g.fillText(label,x+4,y+13)}
 const [ox,oy]=point(0,0);g.save();g.beginPath();const [bx,by]=point(l-200,f+200);g.rect(bx,by,(rr-l+400)*scale,(f+200)*scale);g.clip();g.setLineDash([5,5]);g.strokeStyle='#587081';g.beginPath();for(const sign of [-1,1]){g.moveTo(ox,oy);g.lineTo(...point(sign*6000*Math.sin(Math.PI/3),3000))}g.stroke();g.restore();
 box(game.config.play,'#486677','PLAY AREA');g.strokeStyle='#233b4e';g.lineWidth=1;
 for(let x=Math.ceil(l/500)*500;x<=rr;x+=500){g.beginPath();g.moveTo(...point(x,n));g.lineTo(...point(x,f));g.stroke()}
 for(let y=Math.ceil(n/500)*500;y<=f;y+=500){g.beginPath();g.moveTo(...point(l,y));g.lineTo(...point(rr,y));g.stroke()}
 for(const z of game.zones??[])box(z,'#ff6c75',game.maze?'':'RESTRICTED');box(game.config.start,'#8eb8d2','START');box(game.config.goal,'#79e6c4','VAULT');
 g.fillStyle='#8aa1b6';g.font='11px system-ui';for(const y of [n,f]){const [x,p]=point(l,y);g.fillText((y/1000).toFixed(1)+' m',x-40,p)}
 g.fillStyle='#79e6c4';g.beginPath();g.arc(ox,oy,5,0,Math.PI*2);g.fill();g.textAlign='center';g.fillText('RADAR (0, 0) · +Y ↑',ox,oy+20);g.textAlign='left';
 if(game.valid&&game.point){const [x,y]=point(game.point.x,game.point.y);g.fillStyle='#75d5ff';g.beginPath();g.arc(x,y,7,0,Math.PI*2);g.fill();g.fillStyle='#e8f7ff';g.fillText('PLAYER ESTIMATE',x+10,y-8)}
 else{g.fillStyle='#ffb391';g.fillText('No unambiguous player position',20,20)}
 $('fieldSize').textContent=((rr-l)/1000).toFixed(1)+' × '+((f-n)/1000).toFixed(1)+' m play area';$('fieldDimensions').textContent='X '+l/1000+' to '+rr/1000+' m · Y '+n/1000+' to '+f/1000+' m. ';
}
async function update(){try{const response=await fetch('/api/state');if(!response.ok)throw Error('Service unavailable');snapshot=await response.json();const g=snapshot.game,s=Math.ceil(g.remaining_s);$('timer').textContent=String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0');$('phase').textContent=g.state.toUpperCase();$('suspicion').textContent=Math.round(g.suspicion*100)+'%';$('fill').style.width=(g.suspicion*100)+'%';$('tracking').textContent=g.valid?'One valid player':snapshot.fresh?'Missing / outside / ambiguous':'No fresh samples';$('position').textContent=g.point?`${(g.point.x/1000).toFixed(2)} / ${(g.point.y/1000).toFixed(2)} m`:'—';$('penalties').textContent=`${g.penalties} / ${g.config.max_anomalies}`;$('guideState').textContent=snapshot.guidance_supported?g.guidance.toUpperCase():'Firmware update required';$('rulesText').textContent=`${g.maze?'Crossing a red wall':'A confirmed red-zone entry'} costs ${g.config.penalty_s} seconds. ${g.config.max_anomalies} anomalies trigger lockdown. Clear the zone for ${g.config.cooldown_s} second(s) before another strike. Tracking loss does not pause time.`;document.querySelectorAll('[data-guide]').forEach(b=>b.disabled=g.state!=='running'||!g.valid||!snapshot.guidance_supported);$('led').textContent=snapshot.led+' (device report)';$('connection').textContent=g.valid?'● Tracking live':snapshot.connected?'● Camera connected':'Camera disconnected';$('connection').className='badge '+(g.valid?'live':'bad');
const texts={idle:[g.setup_checked?'Infiltrator to START':'Prepare the play area',g.setup_checked?'Stand inside the marked start region. The navigator starts the round.':'Facilitator: verify orientation, coverage and the marked layout before enabling play.'],running:[g.valid?'Guide your partner':'Tracking uncertain',g.valid?'Guide your partner through the safe route to the vault. Hold a direction to signal; release to STOP.':'Time continues. Return to reliable coverage; a one-second gap faults this attempt.'],won:['Vault reached','Heist complete. Ask the facilitator to reset for the next pair.'],lost:['Lockdown',g.reason+'. Ask the facilitator to reset the room.'],fault:['Attempt invalidated',g.reason+'. Facilitator inspection and reset required.']};[$('headline').textContent,$('message').textContent]=texts[g.state];const b=g.config.start,p=g.point,inStart=p&&p.x>=b[0]&&p.x<=b[1]&&p.y>=b[2]&&p.y<=b[3];$('start').disabled=!(g.state==='idle'&&g.setup_checked&&g.valid&&inStart);$('network').textContent=snapshot.network.enabled?`Public OOCSI ${snapshot.network.connected?'connected':'connecting'} · ${snapshot.network.channel}`:'Local USB mode. Public OOCSI sharing is off.';
$('events').replaceChildren(...g.events.slice().reverse().map(e=>{let li=document.createElement('li');li.textContent=e.event.toUpperCase()+(e.reason?' · '+e.reason:'');return li}));const event=g.events.at(-1);if(event&&lastEvent!==event.at+event.event){if(lastEvent!==null)beep(event.event==='won'?880:event.event==='penalty'?220:440);lastEvent=event.at+event.event}draw();
}catch(e){$('connection').textContent='Toktik service disconnected';$('connection').className='badge bad';$('start').disabled=true;$('headline').textContent='Connection lost';$('message').textContent='The service owns the countdown. Refreshing this page does not reset or pause the round.';snapshot=null;document.querySelectorAll('[data-guide]').forEach(b=>b.disabled=true);releaseGuide();const c=$('map');c.getContext('2d').clearRect(0,0,c.width,c.height);$('tracking').textContent='Unknown';$('position').textContent='—'}setTimeout(update,100)}
$('start').onclick=async()=>{try{const r=await fetch('/api/action',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'start'})});const d=await r.json();$('actionError').textContent=d.error||''}catch(e){$('actionError').textContent=e.message}};
$('sound').onclick=()=>{sound=!sound;$('sound').textContent=sound?'Sound on':'Sound off';if(sound)beep(660)};
window.addEventListener('resize',draw);update();

// Dead-man controls: renew while held; release/focus loss stops, and authority expires stale input.
let heldGuide=null,guideTimer=null,guideBusy=false;
async function sendGuide(direction){if(guideBusy&&direction!=='stop')return;guideBusy=true;try{const r=await fetch('/api/action',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'guide',direction})});const d=await r.json();if(d.error&&direction!=='stop')$('actionError').textContent=d.error;}catch(e){if(direction!=='stop')$('actionError').textContent='Guidance connection lost';}finally{guideBusy=false}}
function releaseGuide(){if(!heldGuide)return;heldGuide=null;clearInterval(guideTimer);sendGuide('stop');}
document.querySelectorAll('[data-guide]').forEach(b=>{b.style.touchAction='none';b.addEventListener('pointerdown',e=>{if(b.disabled)return;e.preventDefault();releaseGuide();heldGuide=b.dataset.guide;b.setPointerCapture(e.pointerId);sendGuide(heldGuide);guideTimer=setInterval(()=>heldGuide&&sendGuide(heldGuide),250);});b.addEventListener('pointerup',releaseGuide);b.addEventListener('pointercancel',releaseGuide);b.addEventListener('lostpointercapture',releaseGuide);b.addEventListener('keydown',e=>{if((e.key===' '||e.key==='Enter')&&!e.repeat&&!b.disabled){e.preventDefault();heldGuide=b.dataset.guide;sendGuide(heldGuide);guideTimer=setInterval(()=>heldGuide&&sendGuide(heldGuide),250);}});b.addEventListener('keyup',releaseGuide);b.addEventListener('blur',releaseGuide);});
window.addEventListener('blur',releaseGuide);document.addEventListener('visibilitychange',()=>{if(document.hidden)releaseGuide()});
